### ISSUE TITLE
2024.1版本报错

### ISSUE THREAD

**Issue by D-Jancy** [wanghuan9/intellij-plugin-save-action-tool#13]
**Describe the bug**
   ```txt
   com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.dubreuia.core.action.ToggleAnAction' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: com.dubreuia.tool]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)
```

**What triggered the plugin**
自动保存格式化时

**Versions**
内部版本号 #IU-241.14494.240，2024年3月28日 构建

**Comment by wanghuan9** [comment]
这个报错 只有在特定场景下才会报, 并不是每次都会报错.   你这边报错的场景可以发我一下吗.  我复现一下

**Comment by D-Jancy** [comment]
> 报这个错只有在特定场景下才会报，不一定每次都会报错。你报错的场景可以发给我一下吗？我复现一下

我也复现不了了

**Comment by wanghuan9** [comment]
好的 感谢反馈. 我再排查一下

**Comment by D-Jancy** [comment]
> 好的 感谢反馈. 我再排查一下

我复现出来了，我在 新建->现有源代码项目 会出现

**Comment by wanghuan9** [comment]
已在 2.6.4  版本修复, 感谢反馈
